name: CI/CD Testing

on:
  push:
    branches: ["main"]

jobs:
  stage-test:
    runs-on: [self-hosted, ORG-STAG-TEST]
    if: github.ref_name == 'main'
    steps:
      - name: Run Test Cases
        run: echo "Test cases run successfully"

  stage-build:
    needs: stage-test
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Node version
        run: node -v

      - name: NPM version
        run: npm -v

      - name: Install Dependencies
        run: npm install --force

      - name: Make Build
        run: npm run buildstage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  stage-deploy:
    needs: stage-build
    runs-on: [self-hosted, ORG-STAG-TEST]
    if: github.ref_name == 'main'
    steps:
      - name: Create deploy directory
        run: |
          sudo mkdir -p /var/www/html/testing/portal
          sudo chown -R $USER:$USER /var/www/html/testing

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: /var/www/html/testing/portal

      - name: Delete Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: dist
